name: Feature Request
description: Suggest a new feature for DexAlarms+
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature for DexAlarms+!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added to DexAlarms+
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: Problem and Solution
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...] / This would help me manage my diabetes better by [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've tried using [...] but it doesn't work well because [...]
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: This feature would be particularly useful in situations like [...]
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
